version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: trs_image_flask
    container_name: trs_flask
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"